# Generated by Django 2.1.4 on 2019-04-25 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mitgliederbereich', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nameMistplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('horsepower', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dienste', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
