# Generated by Django 2.1.4 on 2019-03-08 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reithof_organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pferd',
            name='pferdgruppe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reithof_organizer.Pferdegruppe'),
        ),
    ]
